version : '3'

services:
  spring-crud-db:
    container_name: spring-crud-db
    #using newly created image
    build:
      context: src\main\resources\migrations

    ports:
      - "1521:1521"
      - "5500:5500"
    # mounting volume from our PC (./src/main/resources/db/migrations/scripts) to directory inside the container (/home/oracle/setup/custom_scripts),
    # which we created in Dockerfile
    volumes:
      - ./src/main/resources/migrations/scripts:/home/oracle/setup/custom_scripts
    networks:
      - spring-crud-network
    restart: unless-stopped

networks:
  spring-crud-network:
    driver: bridge